In [ ]:
import numpy as np

In [ ]:
doc = ['go india',
       'india india',
       'hip hip hurray',
       'jeetega bhai jeetega india jeetega',
       'bharat mata ki jai',
       'kohli kohli',
       'sachin sachin',
       'dhoni dhoni',
       'modi ji ki jai',
       'inquilab zindabad']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')
# in tokenizer remove space, convert into lower case like that

In [ ]:
tokenizer.fit_on_texts(doc)

In [ ]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [ ]:
len(tokenizer.word_index)

18

In [ ]:
sequence = tokenizer.texts_to_sequences(doc)
sequence

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
# the above all seqence size is different. to handle this apply padding
from keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [ ]:
sequences = pad_sequences(sequence, padding = 'post')

In [ ]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [ ]:
model = Sequential()

In [ ]:
model.add(Embedding(len(tokenizer.word_index) + 1, output_dim = 2, input_length = 5))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.build(input_shape=(None, sequences.shape[1])) # Build the model with the input shape
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='mse')

In [ ]:
pred = model.predict(sequences)
print(pred)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Create a new Sequential model
model_test = Sequential()

# Add the Embedding layer with the correct vocabulary size
model_test.add(Embedding(len(tokenizer.word_index) + 1, output_dim=2, input_length=5))

# Build the model explicitly
model_test.build(input_shape=(None, sequences.shape[1]))

# Make a prediction using the padded sequences
pred_test = model_test.predict(sequences)
print(pred_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
[[[-0.0110248  -0.04419982]
  [ 0.01137256 -0.01453805]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]]

 [[ 0.01137256 -0.01453805]
  [ 0.01137256 -0.01453805]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]]

 [[-0.012323    0.00251248]
  [-0.012323    0.00251248]
  [ 0.00458742  0.04496868]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]]

 [[-0.01677761  0.04720293]
  [ 0.00267931 -0.02093056]
  [-0.01677761  0.04720293]
  [ 0.01137256 -0.01453805]
  [-0.01677761  0.04720293]]

 [[-0.03061857  0.04230037]
  [ 0.03519006 -0.01044775]
  [-0.02051193  0.0452188 ]
  [-0.04496596 -0.00832809]
  [-0.04760324 -0.03869645]]

 [[-0.04210123 -0.03388661]
  [-0.04210123 -0.03388661]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645]]

 [[ 0.00409405  0.02247666]
  [ 0.00409405  0.02247666]
  [-0.04760324 -0.03869645]
  [-0.04760324 -0.03869645

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
